First cut at linkconfig utilities

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJECT VERSION RELEASE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BASH ENABLE_GENDERS LIBGENDERS PIU_CONFIG_PATH PIU_SBIN_PATH DEBUG_TRUE DEBUG_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJECT VERSION RELEASE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL BASH ibedgeconf_api_version ENABLE_GENDERS LIBGENDERS PIU_CONFIG_PATH PIU_SBIN_PATH DEBUG_TRUE DEBUG_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19183,6 +19183,28 @@ echo "$as_me: error: ibnd_discover_fabric() not found. PIU requires libibnetdisc
 fi
 
 
+echo "$as_me:$LINENO: checking whether ld accepts --version-script" >&5
+echo $ECHO_N "checking whether ld accepts --version-script... $ECHO_C" >&6
+if test "${ac_cv_version_script+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "`$LD --help < /dev/null 2>/dev/null | grep version-script`"; then
+        ac_cv_version_script=yes
+    else
+        ac_cv_version_script=no
+    fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_version_script" >&5
+echo "${ECHO_T}$ac_cv_version_script" >&6
+
+ibedgeconf_api_version=`grep LIBVERSION $srcdir/libibedgeconf.ver | sed 's/LIBVERSION=//'`
+if test -z $ibedgeconf_api_version; then
+   echo "FAILED to find $srcdir/libibedgeconf.ver"
+   exit 1
+fi
+
+
+
 if test $genders = yes; then
 
 echo "$as_me:$LINENO: checking for genders_handle_create in -lgenders" >&5
@@ -20052,6 +20074,7 @@ s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@BASH@,$BASH,;t t
+s,@ibedgeconf_api_version@,$ibedgeconf_api_version,;t t
 s,@ENABLE_GENDERS@,$ENABLE_GENDERS,;t t
 s,@LIBGENDERS@,$LIBGENDERS,;t t
 s,@PIU_CONFIG_PATH@,$PIU_CONFIG_PATH,;t t
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -37,6 +37,21 @@ AC_CHECK_LIB(rdmacm, rdma_connect, [],
 AC_CHECK_LIB(ibnetdisc, ibnd_discover_fabric, [],
         AC_MSG_ERROR([ibnd_discover_fabric() not found. PIU requires libibnetdisc.]))
 
+AC_CACHE_CHECK(whether ld accepts --version-script, ac_cv_version_script,
+    if test -n "`$LD --help < /dev/null 2>/dev/null | grep version-script`"; then
+        ac_cv_version_script=yes
+    else
+        ac_cv_version_script=no
+    fi)
+
+ibedgeconf_api_version=`grep LIBVERSION $srcdir/libibedgeconf.ver | sed 's/LIBVERSION=//'`
+if test -z $ibedgeconf_api_version; then
+   echo "FAILED to find $srcdir/libibedgeconf.ver"
+   exit 1
+fi
+AC_SUBST(ibedgeconf_api_version)
+
+
 if test $genders = yes; then
 AC_CHECK_LIB(genders, genders_handle_create, [],
         AC_MSG_ERROR([genders_handle_create() not found.  To disable genders use --disable-genders]))
