ibsrp: fix issue where 1 port is Eth and the other IB
Signed-off-by: Ira Weiny <weiny2@llnl.gov>

diff --git a/scripts/ibsrp.in b/scripts/ibsrp.in
--- a/scripts/ibsrp.in
+++ b/scripts/ibsrp.in
@@ -38,45 +38,44 @@ is_module()
 startOpenSMCA2CA()
 {
     for ch_adaptor in `ibstat -l`; do
-      if [ `ibstat $ch_adaptor | grep -c 'Link layer: Ethernet'` -ne 0 ]; then
-        $log_cmd "Adaptor $ch_adaptor is an ethernet device... Skipping smquery."
-      else
-        ibstat $ch_adaptor | grep Port | grep -v GUID | cut -d ":" -f 1 | cut -d " " -f 2 | \
-            while read port
-        do
-           # find if this port is connected to a CA or a switch
-           smpquery -C $ch_adaptor -P $port -D nodeinfo 0,$port 2> /dev/null | grep NodeType | grep "Channel Adapter" > /dev/null
-           ca=`echo $?`
-           if [ "$ca" == "1" ]; then
-               $log_cmd "Port $ch_adaptor:$port is not connected to a Channel Adaptor...  Skipping"
-               continue
-           fi
+      numport=`ibstat $ch_adaptor | grep Number | sed -e "s/.*:\(.*\)/\1/"`
+      for port in `seq 1 $numport`; do
+         if [ `ibstat $ch_adaptor $port | grep -c 'Link layer: Ethernet'` -ne 0 ]; then
+            $log_cmd "Adaptor $ch_adaptor port $port is an ethernet port... Skipping smpquery."
+         else
+            # find if this port is connected to a CA or a switch
+            smpquery -C $ch_adaptor -P $port -D nodeinfo 0,$port 2> /dev/null | grep NodeType | grep "Channel Adapter" > /dev/null
+            ca=`echo $?`
+            if [ "$ca" == "1" ]; then
+                $log_cmd "Port $ch_adaptor:$port is not connected to a Channel Adaptor...  Skipping"
+                continue
+            fi
 
-           # check for an SM on the other end of the link.
-           smpquery -C $ch_adaptor -P $port -D portinfo 0,$port 2> /dev/null | grep IsSM
-           sm=`echo $?`
-           if [ "$sm" == "0" ]; then
-               # if the other end provides an SM we don't need to bother
-               $log_cmd "Port $ch_adaptor:$port is connected to a Channel Adaptor which is SM capable...  Skipping OpenSM start"
-               continue
-           fi
+            # check for an SM on the other end of the link.
+            smpquery -C $ch_adaptor -P $port -D portinfo 0,$port 2> /dev/null | grep IsSM
+            sm=`echo $?`
+            if [ "$sm" == "0" ]; then
+                # if the other end provides an SM we don't need to bother
+                $log_cmd "Port $ch_adaptor:$port is connected to a Channel Adaptor which is SM capable...  Skipping OpenSM start"
+                continue
+            fi
 
-           port_guid=`smpquery -C $ch_adaptor -P $port -D nodeinfo 0 | grep PortGuid | sed -e "s/^PortGuid:\.*\(.*\)/\1/"`
-           if [ "$port_guid" != "" ] ; then
-               $log_cmd "Starting OpenSM on port $ch_adaptor:$port (guid $port_guid)"
-               opensm -g $port_guid -s 300 -f $LOG_DIR/opensm-$port.log 2>&1 > $LOG_DIR/opensm-$port.log &
-               pid=$!
-               sleep $OPENSM_SETTLE_TIMEOUT
-               run=`ps -p $pid -o comm=`
-               if [ x$run == x ]; then
-                    $log_cmd "Failed to start opensm; port $ch_adaptor:$port, guid $port_guid: see $LOG_DIR/opensm-$port.log"
-                    echo_failure
-                    exit 1
-               fi
-               echo $pid >> $PID_DIR/opensm.pid
-           fi
-        done
-      fi
+            port_guid=`smpquery -C $ch_adaptor -P $port -D nodeinfo 0 | grep PortGuid | sed -e "s/^PortGuid:\.*\(.*\)/\1/"`
+            if [ "$port_guid" != "" ] ; then
+                $log_cmd "Starting OpenSM on port $ch_adaptor:$port (guid $port_guid)"
+                opensm -g $port_guid -s 300 -f $LOG_DIR/opensm-$port.log 2>&1 > $LOG_DIR/opensm-$port.log &
+                pid=$!
+                sleep $OPENSM_SETTLE_TIMEOUT
+                run=`ps -p $pid -o comm=`
+                if [ x$run == x ]; then
+                     $log_cmd "Failed to start opensm; port $ch_adaptor:$port, guid $port_guid: see $LOG_DIR/opensm-$port.log"
+                     echo_failure
+                     exit 1
+                fi
+                echo $pid >> $PID_DIR/opensm.pid
+            fi
+         fi
+      done
     done
 }
 
